my_share_hek added
Needed to re-hash PL_strtab dynamically, not to conflict old with new hash keys.
Error: Assertion he->shared_he_he.hent_hek == hek failed